In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from sklearn.linear_model import LogisticRegression #logistic regression
from sklearn import svm #support vector Machine
from sklearn.ensemble import RandomForestClassifier #Random Forest
from sklearn.neighbors import KNeighborsClassifier #KNN
from sklearn.naive_bayes import GaussianNB #Naive bayes
from sklearn.tree import DecisionTreeClassifier #Decision Tree
from sklearn.ensemble import GradientBoostingClassifier 
from sklearn.ensemble import AdaBoostClassifier 
from sklearn.model_selection import train_test_split as tts #training and testing data split
from sklearn import metrics #accuracy measure
from sklearn.metrics import confusion_matrix #for confusion matrix

In [2]:
df=pd.read_csv('Loan_prep.csv')

In [3]:
df=df.drop(['Unnamed: 0'],axis=1)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215700 entries, 0 to 215699
Data columns (total 25 columns):
Loan_ID                         215700 non-null object
Customer_ID                     215700 non-null object
Loan_Status                     215700 non-null object
Current_Loan_Amount             215700 non-null float64
Term                            215700 non-null object
Credit_Score                    215700 non-null float64
Years_in_current_job            215700 non-null int64
Home_Ownership                  215700 non-null object
Annual_Income                   215700 non-null float64
Purpose                         215700 non-null object
Monthly_Debt                    215700 non-null float64
Years_of_Credit_History         215700 non-null float64
Months_since_last_delinquent    97438 non-null float64
Number_of_Open_Accounts         215700 non-null int64
Number_of_Credit_Problems       215700 non-null int64
Current_Credit_Balance          215700 non-null float64
Maximum_Open_Credit             215700 non-null float64
Bankruptcies                    215700 non-null float64
Tax_Liens                       215700 non-null float64
Current_Loan_Amount_log         215700 non-null float64
Current_Credit_Balance_log      215700 non-null float64
Maximum_Open_Credit_log         215700 non-null float64
Monthly_Debt_log                215700 non-null float64
Credit_Score_log                215700 non-null float64
Annual_Income_log               215700 non-null float64
dtypes: float64(16), int64(3), object(6)
memory usage: 41.1+ MB

In [5]:
df['Monthly_Income']=df.loc[:,'Annual_Income']/12

In [6]:
df['di_ratio']=df['Monthly_Debt']/df['Monthly_Income']

In [7]:
df[pd.isnull(df['di_ratio'])]

,Loan_ID,Customer_ID,Loan_Status,Current_Loan_Amount,Term,Credit_Score,Years_in_current_job,Home_Ownership,Annual_Income,Purpose,...,Bankruptcies,Tax_Liens,Current_Loan_Amount_log,Current_Credit_Balance_log,Maximum_Open_Credit_log,Monthly_Debt_log,Credit_Score_log,Annual_Income_log,Monthly_Income,di_ratio
181407,2025adf8-360c-4229-afd6-d282b6f1e29e,77538d62-ee55-4f45-9949-1b91f3acf420,Charged Off,3622.0,Short Term,731.0,0,Home Mortgage,0.0,Debt Consolidation,...,0.0,0.0,8.195058,9.251866,9.815694,0.0,6.594413,0.0,0.0,NaN

In [8]:
list(df[pd.isnull(df['di_ratio'])])

['Loan_ID',
 'Customer_ID',
 'Loan_Status',
 'Current_Loan_Amount',
 'Term',
 'Credit_Score',
 'Years_in_current_job',
 'Home_Ownership',
 'Annual_Income',
 'Purpose',
 'Monthly_Debt',
 'Years_of_Credit_History',
 'Months_since_last_delinquent',
 'Number_of_Open_Accounts',
 'Number_of_Credit_Problems',
 'Current_Credit_Balance',
 'Maximum_Open_Credit',
 'Bankruptcies',
 'Tax_Liens',
 'Current_Loan_Amount_log',
 'Current_Credit_Balance_log',
 'Maximum_Open_Credit_log',
 'Monthly_Debt_log',
 'Credit_Score_log',
 'Annual_Income_log',
 'Monthly_Income',
 'di_ratio']

In [9]:
df.iloc[:, 26] = df.iloc[:, 26].fillna(df['di_ratio'].mean())

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215700 entries, 0 to 215699
Data columns (total 27 columns):
Loan_ID                         215700 non-null object
Customer_ID                     215700 non-null object
Loan_Status                     215700 non-null object
Current_Loan_Amount             215700 non-null float64
Term                            215700 non-null object
Credit_Score                    215700 non-null float64
Years_in_current_job            215700 non-null int64
Home_Ownership                  215700 non-null object
Annual_Income                   215700 non-null float64
Purpose                         215700 non-null object
Monthly_Debt                    215700 non-null float64
Years_of_Credit_History         215700 non-null float64
Months_since_last_delinquent    97438 non-null float64
Number_of_Open_Accounts         215700 non-null int64
Number_of_Credit_Problems       215700 non-null int64
Current_Credit_Balance          215700 non-null float64
Maximum_Open_Credit             215700 non-null float64
Bankruptcies                    215700 non-null float64
Tax_Liens                       215700 non-null float64
Current_Loan_Amount_log         215700 non-null float64
Current_Credit_Balance_log      215700 non-null float64
Maximum_Open_Credit_log         215700 non-null float64
Monthly_Debt_log                215700 non-null float64
Credit_Score_log                215700 non-null float64
Annual_Income_log               215700 non-null float64
Monthly_Income                  215700 non-null float64
di_ratio                        215700 non-null float64
dtypes: float64(18), int64(3), object(6)
memory usage: 44.4+ MB

In [11]:
df=df.drop(['Loan_ID',
 'Customer_ID',
 'Annual_Income',
 'Credit_Score',
 'Current_Loan_Amount_log','Current_Credit_Balance','Maximum_Open_Credit',
 'Monthly_Debt','Credit_Score','Annual_Income','Monthly_Income','Months_since_last_delinquent'],axis=1)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215700 entries, 0 to 215699
Data columns (total 17 columns):
Loan_Status                   215700 non-null object
Current_Loan_Amount           215700 non-null float64
Term                          215700 non-null object
Years_in_current_job          215700 non-null int64
Home_Ownership                215700 non-null object
Purpose                       215700 non-null object
Years_of_Credit_History       215700 non-null float64
Number_of_Open_Accounts       215700 non-null int64
Number_of_Credit_Problems     215700 non-null int64
Bankruptcies                  215700 non-null float64
Tax_Liens                     215700 non-null float64
Current_Credit_Balance_log    215700 non-null float64
Maximum_Open_Credit_log       215700 non-null float64
Monthly_Debt_log              215700 non-null float64
Credit_Score_log              215700 non-null float64
Annual_Income_log             215700 non-null float64
di_ratio                      215700 non-null float64
dtypes: float64(10), int64(3), object(4)
memory usage: 28.0+ MB

In [13]:
df['Number_of_Open_Accounts'] = df['Number_of_Open_Accounts'].astype('object')
df['Number_of_Credit_Problems'] = df['Number_of_Credit_Problems'].astype('object')
df['Bankruptcies'] = df['Bankruptcies'].astype('object')
df['Tax_Liens'] = df['Tax_Liens'].astype('object')
df['Years_in_current_job'] = df['Years_in_current_job'].astype('object')

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215700 entries, 0 to 215699
Data columns (total 17 columns):
Loan_Status                   215700 non-null object
Current_Loan_Amount           215700 non-null float64
Term                          215700 non-null object
Years_in_current_job          215700 non-null object
Home_Ownership                215700 non-null object
Purpose                       215700 non-null object
Years_of_Credit_History       215700 non-null float64
Number_of_Open_Accounts       215700 non-null object
Number_of_Credit_Problems     215700 non-null object
Bankruptcies                  215700 non-null object
Tax_Liens                     215700 non-null object
Current_Credit_Balance_log    215700 non-null float64
Maximum_Open_Credit_log       215700 non-null float64
Monthly_Debt_log              215700 non-null float64
Credit_Score_log              215700 non-null float64
Annual_Income_log             215700 non-null float64
di_ratio                      215700 non-null float64
dtypes: float64(8), object(9)
memory usage: 28.0+ MB

In [15]:
prep2=df.copy()

# scaling

In [16]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.model_selection import KFold

In [17]:
scaler = StandardScaler()
prep2[['Current_Loan_Amount', 'Years_of_Credit_History']] = scaler.fit_transform(prep2[['Current_Loan_Amount', 'Years_of_Credit_History']])
prep2.head(5)

,Loan_Status,Current_Loan_Amount,Term,Years_in_current_job,Home_Ownership,Purpose,Years_of_Credit_History,Number_of_Open_Accounts,Number_of_Credit_Problems,Bankruptcies,Tax_Liens,Current_Credit_Balance_log,Maximum_Open_Credit_log,Monthly_Debt_log,Credit_Score_log,Annual_Income_log,di_ratio
0,Fully Paid,-0.003618,Short Term,10,Home Mortgage,Debt Consolidation,-0.858568,10,0,0,0,8.818926,9.683900,6.371663,6.608001,10.425105,0.208000
1,Fully Paid,-0.893036,Short Term,4,Home Mortgage,other,1.125002,17,0,0,0,8.742415,9.860058,7.009445,6.598509,10.651833,0.314000
2,Fully Paid,1.043230,Short Term,10,Home Mortgage,Debt Consolidation,1.479210,5,0,0,0,9.950753,10.251888,7.187544,6.616065,11.408975,0.176000
3,Fully Paid,0.791564,Short Term,10,Own Home,Debt Consolidation,1.110833,9,0,0,0,10.022603,10.690034,6.623959,6.616065,10.547261,0.236999
4,Fully Paid,0.019611,Short Term,4,Rent,Debt Consolidation,-0.971915,12,0,0,0,9.763766,10.520887,5.875436,6.614726,10.820298,0.085201

In [18]:
lib={'Fully Paid':0,'Charged Off':1 }
prep2.Loan_Status=prep2.Loan_Status.map(lib)

In [19]:
prep2.dtypes

Loan_Status                     int64
Current_Loan_Amount           float64
Term                           object
Years_in_current_job           object
Home_Ownership                 object
Purpose                        object
Years_of_Credit_History       float64
Number_of_Open_Accounts        object
Number_of_Credit_Problems      object
Bankruptcies                   object
Tax_Liens                      object
Current_Credit_Balance_log    float64
Maximum_Open_Credit_log       float64
Monthly_Debt_log              float64
Credit_Score_log              float64
Annual_Income_log             float64
di_ratio                      float64
dtype: object

In [20]:
dummy_prep2=pd.get_dummies(prep2,drop_first=False)

In [21]:
dummy_prep2.head()

,Loan_Status,Current_Loan_Amount,Years_of_Credit_History,Current_Credit_Balance_log,Maximum_Open_Credit_log,Monthly_Debt_log,Credit_Score_log,Annual_Income_log,di_ratio,Term_Long Term,...,Tax_Liens_2.0,Tax_Liens_3.0,Tax_Liens_4.0,Tax_Liens_5.0,Tax_Liens_6.0,Tax_Liens_7.0,Tax_Liens_8.0,Tax_Liens_9.0,Tax_Liens_10.0,Tax_Liens_11.0
0,0,-0.003618,-0.858568,8.818926,9.683900,6.371663,6.608001,10.425105,0.208000,0,...,0,0,0,0,0,0,0,0,0,0
1,0,-0.893036,1.125002,8.742415,9.860058,7.009445,6.598509,10.651833,0.314000,0,...,0,0,0,0,0,0,0,0,0,0
2,0,1.043230,1.479210,9.950753,10.251888,7.187544,6.616065,11.408975,0.176000,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0.791564,1.110833,10.022603,10.690034,6.623959,6.616065,10.547261,0.236999,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0.019611,-0.971915,9.763766,10.520887,5.875436,6.614726,10.820298,0.085201,0,...,0,0,0,0,0,0,0,0,0,0

In [22]:
list(dummy_prep2.columns)

['Loan_Status',
 'Current_Loan_Amount',
 'Years_of_Credit_History',
 'Current_Credit_Balance_log',
 'Maximum_Open_Credit_log',
 'Monthly_Debt_log',
 'Credit_Score_log',
 'Annual_Income_log',
 'di_ratio',
 'Term_Long Term',
 'Term_Short Term',
 'Years_in_current_job_0',
 'Years_in_current_job_1',
 'Years_in_current_job_2',
 'Years_in_current_job_3',
 'Years_in_current_job_4',
 'Years_in_current_job_5',
 'Years_in_current_job_6',
 'Years_in_current_job_7',
 'Years_in_current_job_8',
 'Years_in_current_job_9',
 'Years_in_current_job_10',
 'Home_Ownership_Home Mortgage',
 'Home_Ownership_Own Home',
 'Home_Ownership_Rent',
 'Purpose_Business Loan',
 'Purpose_Buy House',
 'Purpose_Buy a Car',
 'Purpose_Debt Consolidation',
 'Purpose_Educational Expenses',
 'Purpose_Home Improvements',
 'Purpose_Medical Bills',
 'Purpose_Other',
 'Purpose_Take a Trip',
 'Purpose_other',
 'Number_of_Open_Accounts_0',
 'Number_of_Open_Accounts_1',
 'Number_of_Open_Accounts_2',
 'Number_of_Open_Accounts_3',
 'Number_of_Open_Accounts_4',
 'Number_of_Open_Accounts_5',
 'Number_of_Open_Accounts_6',
 'Number_of_Open_Accounts_7',
 'Number_of_Open_Accounts_8',
 'Number_of_Open_Accounts_9',
 'Number_of_Open_Accounts_10',
 'Number_of_Open_Accounts_11',
 'Number_of_Open_Accounts_12',
 'Number_of_Open_Accounts_13',
 'Number_of_Open_Accounts_14',
 'Number_of_Open_Accounts_15',
 'Number_of_Open_Accounts_16',
 'Number_of_Open_Accounts_17',
 'Number_of_Open_Accounts_18',
 'Number_of_Open_Accounts_19',
 'Number_of_Open_Accounts_20',
 'Number_of_Open_Accounts_21',
 'Number_of_Open_Accounts_22',
 'Number_of_Open_Accounts_23',
 'Number_of_Open_Accounts_24',
 'Number_of_Open_Accounts_25',
 'Number_of_Open_Accounts_26',
 'Number_of_Open_Accounts_27',
 'Number_of_Open_Accounts_28',
 'Number_of_Open_Accounts_29',
 'Number_of_Open_Accounts_30',
 'Number_of_Open_Accounts_31',
 'Number_of_Open_Accounts_32',
 'Number_of_Open_Accounts_33',
 'Number_of_Open_Accounts_34',
 'Number_of_Open_Accounts_35',
 'Number_of_Open_Accounts_36',
 'Number_of_Open_Accounts_37',
 'Number_of_Open_Accounts_38',
 'Number_of_Open_Accounts_39',
 'Number_of_Open_Accounts_40',
 'Number_of_Open_Accounts_41',
 'Number_of_Open_Accounts_42',
 'Number_of_Open_Accounts_43',
 'Number_of_Open_Accounts_44',
 'Number_of_Open_Accounts_45',
 'Number_of_Open_Accounts_46',
 'Number_of_Open_Accounts_47',
 'Number_of_Open_Accounts_48',
 'Number_of_Open_Accounts_49',
 'Number_of_Open_Accounts_50',
 'Number_of_Open_Accounts_51',
 'Number_of_Open_Accounts_52',
 'Number_of_Open_Accounts_53',
 'Number_of_Open_Accounts_54',
 'Number_of_Open_Accounts_55',
 'Number_of_Open_Accounts_56',
 'Number_of_Open_Accounts_58',
 'Number_of_Open_Accounts_76',
 'Number_of_Credit_Problems_0',
 'Number_of_Credit_Problems_1',
 'Number_of_Credit_Problems_2',
 'Number_of_Credit_Problems_3',
 'Number_of_Credit_Problems_4',
 'Number_of_Credit_Problems_5',
 'Number_of_Credit_Problems_6',
 'Number_of_Credit_Problems_7',
 'Number_of_Credit_Problems_8',
 'Number_of_Credit_Problems_9',
 'Number_of_Credit_Problems_10',
 'Number_of_Credit_Problems_11',
 'Bankruptcies_0.0',
 'Bankruptcies_0.110556195644',
 'Bankruptcies_1.0',
 'Bankruptcies_2.0',
 'Bankruptcies_3.0',
 'Bankruptcies_4.0',
 'Bankruptcies_5.0',
 'Bankruptcies_6.0',
 'Bankruptcies_7.0',
 'Tax_Liens_0.0',
 'Tax_Liens_0.0263309192407',
 'Tax_Liens_1.0',
 'Tax_Liens_2.0',
 'Tax_Liens_3.0',
 'Tax_Liens_4.0',
 'Tax_Liens_5.0',
 'Tax_Liens_6.0',
 'Tax_Liens_7.0',
 'Tax_Liens_8.0',
 'Tax_Liens_9.0',
 'Tax_Liens_10.0',
 'Tax_Liens_11.0']

In [23]:
#cat_data=['attribute4','attribute5','device_type','att2','att39','att78','month']
#onehotencoder = OneHotEncoder(categorical_features = [0,2,3,4,5,7,8,9,10])
#prep_enc = onehotencoder.fit_transform(prep2).toarray()
#prep_enc

In [24]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler

labelencoder = LabelEncoder()
prep2.loc[:, 'Term'] = labelencoder.fit_transform(prep2.loc[:, 'Term'])
prep2.loc[:, 'Years_in_current_job'] = labelencoder.fit_transform(prep2.loc[:, 'Years_in_current_job'])
prep2.loc[:, 'Home_Ownership'] = labelencoder.fit_transform(prep2.loc[:, 'Home_Ownership'])
prep2.loc[:, 'Purpose'] = labelencoder.fit_transform(prep2.loc[:, 'Purpose'])
prep2.loc[:, 'Number_of_Open_Accounts'] = labelencoder.fit_transform(prep2.loc[:, 'Number_of_Open_Accounts'])
prep2.loc[:, 'Number_of_Credit_Problems'] = labelencoder.fit_transform(prep2.loc[:, 'Number_of_Credit_Problems'])
prep2.loc[:, 'Bankruptcies'] = labelencoder.fit_transform(prep2.loc[:, 'Bankruptcies'])
prep2.loc[:, 'Tax_Liens'] = labelencoder.fit_transform(prep2.loc[:, 'Tax_Liens'])

In [25]:
prep2.head()

,Loan_Status,Current_Loan_Amount,Term,Years_in_current_job,Home_Ownership,Purpose,Years_of_Credit_History,Number_of_Open_Accounts,Number_of_Credit_Problems,Bankruptcies,Tax_Liens,Current_Credit_Balance_log,Maximum_Open_Credit_log,Monthly_Debt_log,Credit_Score_log,Annual_Income_log,di_ratio
0,0,-0.003618,1,10,0,3,-0.858568,10,0,0,0,8.818926,9.683900,6.371663,6.608001,10.425105,0.208000
1,0,-0.893036,1,4,0,9,1.125002,17,0,0,0,8.742415,9.860058,7.009445,6.598509,10.651833,0.314000
2,0,1.043230,1,10,0,3,1.479210,5,0,0,0,9.950753,10.251888,7.187544,6.616065,11.408975,0.176000
3,0,0.791564,1,10,1,3,1.110833,9,0,0,0,10.022603,10.690034,6.623959,6.616065,10.547261,0.236999
4,0,0.019611,1,4,2,3,-0.971915,12,0,0,0,9.763766,10.520887,5.875436,6.614726,10.820298,0.085201

In [26]:
prep2.dtypes

Loan_Status                     int64
Current_Loan_Amount           float64
Term                            int64
Years_in_current_job            int64
Home_Ownership                  int64
Purpose                         int64
Years_of_Credit_History       float64
Number_of_Open_Accounts         int64
Number_of_Credit_Problems       int64
Bankruptcies                    int64
Tax_Liens                       int64
Current_Credit_Balance_log    float64
Maximum_Open_Credit_log       float64
Monthly_Debt_log              float64
Credit_Score_log              float64
Annual_Income_log             float64
di_ratio                      float64
dtype: object

In [27]:
onehotencoder = OneHotEncoder(categorical_features = [2,3,4,5,7,8,9,10])
prep_enc = onehotencoder.fit_transform(prep2).toarray()
prep_enc

array([[  0.00000000e+00,   1.00000000e+00,   0.00000000e+00, ...,
          6.60800063e+00,   1.04251047e+01,   2.08000237e-01],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00, ...,
          6.59850903e+00,   1.06518329e+01,   3.14000331e-01],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00, ...,
          6.61606519e+00,   1.14089751e+01,   1.76000266e-01],
       ...,
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00, ...,
          6.55108034e+00,   1.19100627e+01,   3.80034285e-03],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00, ...,
          5.97723884e+00,   1.05927522e+01,   2.96000402e-01],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00, ...,
          6.01688860e+00,   1.08686637e+01,   6.80999543e-02]])

In [28]:
dummy=pd.DataFrame(columns=['Loan_Status',
 'Term_Long Term',
 'Term_Short Term',
 'Years_in_current_job_0',
 'Years_in_current_job_1',
 'Years_in_current_job_2',
 'Years_in_current_job_3',
 'Years_in_current_job_4',
 'Years_in_current_job_5',
 'Years_in_current_job_6',
 'Years_in_current_job_7',
 'Years_in_current_job_8',
 'Years_in_current_job_9',
 'Years_in_current_job_10',
 'Home_Ownership_Home Mortgage',
 'Home_Ownership_Own Home',
 'Home_Ownership_Rent',
 'Purpose_Business Loan',
 'Purpose_Buy House',
 'Purpose_Buy a Car',
 'Purpose_Debt Consolidation',
 'Purpose_Educational Expenses',
 'Purpose_Home Improvements',
 'Purpose_Medical Bills',
 'Purpose_Other',
 'Purpose_Take a Trip',
 'Purpose_other',
 'Number_of_Open_Accounts_0',
 'Number_of_Open_Accounts_1',
 'Number_of_Open_Accounts_2',
 'Number_of_Open_Accounts_3',
 'Number_of_Open_Accounts_4',
 'Number_of_Open_Accounts_5',
 'Number_of_Open_Accounts_6',
 'Number_of_Open_Accounts_7',
 'Number_of_Open_Accounts_8',
 'Number_of_Open_Accounts_9',
 'Number_of_Open_Accounts_10',
 'Number_of_Open_Accounts_11',
 'Number_of_Open_Accounts_12',
 'Number_of_Open_Accounts_13',
 'Number_of_Open_Accounts_14',
 'Number_of_Open_Accounts_15',
 'Number_of_Open_Accounts_16',
 'Number_of_Open_Accounts_17',
 'Number_of_Open_Accounts_18',
 'Number_of_Open_Accounts_19',
 'Number_of_Open_Accounts_20',
 'Number_of_Open_Accounts_21',
 'Number_of_Open_Accounts_22',
 'Number_of_Open_Accounts_23',
 'Number_of_Open_Accounts_24',
 'Number_of_Open_Accounts_25',
 'Number_of_Open_Accounts_26',
 'Number_of_Open_Accounts_27',
 'Number_of_Open_Accounts_28',
 'Number_of_Open_Accounts_29',
 'Number_of_Open_Accounts_30',
 'Number_of_Open_Accounts_31',
 'Number_of_Open_Accounts_32',
 'Number_of_Open_Accounts_33',
 'Number_of_Open_Accounts_34',
 'Number_of_Open_Accounts_35',
 'Number_of_Open_Accounts_36',
 'Number_of_Open_Accounts_37',
 'Number_of_Open_Accounts_38',
 'Number_of_Open_Accounts_39',
 'Number_of_Open_Accounts_40',
 'Number_of_Open_Accounts_41',
 'Number_of_Open_Accounts_42',
 'Number_of_Open_Accounts_43',
 'Number_of_Open_Accounts_44',
 'Number_of_Open_Accounts_45',
 'Number_of_Open_Accounts_46',
 'Number_of_Open_Accounts_47',
 'Number_of_Open_Accounts_48',
 'Number_of_Open_Accounts_49',
 'Number_of_Open_Accounts_50',
 'Number_of_Open_Accounts_51',
 'Number_of_Open_Accounts_52',
 'Number_of_Open_Accounts_53',
 'Number_of_Open_Accounts_54',
 'Number_of_Open_Accounts_55',
 'Number_of_Open_Accounts_56',
 'Number_of_Open_Accounts_58',
 'Number_of_Open_Accounts_76',
 'Number_of_Credit_Problems_0',
 'Number_of_Credit_Problems_1',
 'Number_of_Credit_Problems_2',
 'Number_of_Credit_Problems_3',
 'Number_of_Credit_Problems_4',
 'Number_of_Credit_Problems_5',
 'Number_of_Credit_Problems_6',
 'Number_of_Credit_Problems_7',
 'Number_of_Credit_Problems_8',
 'Number_of_Credit_Problems_9',
 'Number_of_Credit_Problems_10',
 'Number_of_Credit_Problems_11',
 'Bankruptcies_0.0',
 'Bankruptcies_0.110556195644',
 'Bankruptcies_1.0',
 'Bankruptcies_2.0',
 'Bankruptcies_3.0',
 'Bankruptcies_4.0',
 'Bankruptcies_5.0',
 'Bankruptcies_6.0',
 'Bankruptcies_7.0',
 'Tax_Liens_0.0',
 'Tax_Liens_0.0263309192407',
 'Tax_Liens_1.0',
 'Tax_Liens_2.0',
 'Tax_Liens_3.0',
 'Tax_Liens_4.0',
 'Tax_Liens_5.0',
 'Tax_Liens_6.0',
 'Tax_Liens_7.0',
 'Tax_Liens_8.0',
 'Tax_Liens_9.0',
 'Tax_Liens_10.0',
 'Tax_Liens_11.0',
 'Current_Loan_Amount',
 'Years_of_Credit_History',
 'Current_Credit_Balance_log',
 'Maximum_Open_Credit_log',
 'Monthly_Debt_log',
 'Credit_Score_log',
 'Annual_Income_log',
 'di_ratio'])

In [29]:
data_scaled = pd.DataFrame(prep_enc,columns= dummy.columns)

In [30]:
data_scaled.head(50)

,Loan_Status,Term_Long Term,Term_Short Term,Years_in_current_job_0,Years_in_current_job_1,Years_in_current_job_2,Years_in_current_job_3,Years_in_current_job_4,Years_in_current_job_5,Years_in_current_job_6,...,Tax_Liens_10.0,Tax_Liens_11.0,Current_Loan_Amount,Years_of_Credit_History,Current_Credit_Balance_log,Maximum_Open_Credit_log,Monthly_Debt_log,Credit_Score_log,Annual_Income_log,di_ratio
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-0.003618,-0.858568,8.818926,9.683900,6.371663,6.608001,10.425105,0.208000
1,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,-0.893036,1.125002,8.742415,9.860058,7.009445,6.598509,10.651833,0.314000
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.043230,1.479210,9.950753,10.251888,7.187544,6.616065,11.408975,0.176000
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.791564,1.110833,10.022603,10.690034,6.623959,6.616065,10.547261,0.236999
4,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.019611,-0.971915,9.763766,10.520887,5.875436,6.614726,10.820298,0.085201
5,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-0.148056,-0.731053,7.736307,8.449343,6.332427,6.573680,10.641943,0.160998
6,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,-0.166991,-0.093477,9.390242,9.715952,5.959354,6.553769,11.013933,0.076364
7,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-1.047713,0.204059,9.298992,9.659950,6.610413,6.597146,10.932857,0.158998
8,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-1.271857,1.195843,9.091669,10.030649,6.369627,6.609349,11.078459,0.108000
9,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-0.145304,0.119048,10.393018,10.638904,7.361579,6.609349,11.941430,0.123000
10,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,-1.271857,0.374079,9.351406,9.756321,6.892713,6.612041,11.091422,0.179999
11,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,-0.436602,0.062375,9.050172,9.679281,6.113682,6.612041,10.831331,0.106999
12,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-0.476125,-0.079308,9.046526,9.671997,6.088047,6.567204,11.305838,0.064885
13,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-1.271857,-0.419349,8.441823,9.960435,6.183283,6.613384,10.583474,0.147000
14,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.034143,1.691736,9.206332,9.740733,6.757235,6.598509,11.144799,0.149000
15,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.422982,0.218227,7.689371,9.103868,6.168627,6.597146,10.858710,0.110002
16,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-0.764121,-0.617706,9.096051,9.141097,5.573180,6.552528,11.124890,0.046394
17,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.589328,1.592557,10.762192,10.898016,7.690199,6.590301,12.230380,0.128000
18,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-1.271857,-0.674379,8.812992,10.884367,6.657215,6.584791,10.442842,0.271993
19,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.498394,-0.646043,9.118992,9.522447,5.777188,6.539586,11.055893,0.061000
20,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-0.112717,-0.405181,10.104876,10.654739,6.987416,6.605298,10.945441,0.229002
21,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-1.114097,-0.461854,10.229440,10.811020,7.874268,6.573680,11.596678,0.290000
22,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.652960,-0.093477,10.635952,10.735788,7.471551,6.408529,11.250534,0.273998
23,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-0.709186,-0.306002,10.193280,10.590793,6.841947,6.599870,10.736397,0.243999
24,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-0.598765,-0.079308,8.660947,9.545097,5.337394,6.560765,11.176688,0.034763
25,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-0.400933,1.252517,7.959975,9.280239,6.219994,6.591674,9.799570,0.334003
26,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-1.271857,0.515762,8.283999,11.064495,4.050219,6.620073,11.371201,0.007800
27,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,2.389853,-0.603538,9.591103,10.272289,7.037405,6.602588,11.341603,0.162000
28,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.475825,1.096665,9.352447,11.916348,7.488271,6.614726,11.505105,0.216000
29,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-0.026406,0.671614,8.952088,9.401456,7.131922,6.608001,11.298048,0.186001
30,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-0.885660,1.450874,9.362546,10.145531,5.944163,6.601230,11.352663,0.053600
31,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.540177,0.898308,9.741498,10.405050,7.303756,6.614726,11.311262,0.218000
32,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,-1.271857,0.742456,8.665441,8.759669,5.634932,6.605298,11.013056,0.055201
33,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.941786,-0.646043,10.063649,10.414633,7.100530,6.572283,11.436131,0.157000
34,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-0.568380,-1.071093,8.472614,8.796944,5.684362,6.612041,10.632171,0.084900
35,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,-0.248348,-1.467807,8.685754,9.000360,6.139324,6.588926,10.609872,0.137000
36,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,-0.198037,0.005702,10.115206,10.577223,6.562684,6.610696,11.200349,0.116001
37,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-0.493739,0.416584,8.337827,8.832150,6.056034,6.549916,10.726918,0.112107
38,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-1.271857,1.252517,8.076205,9.411484,6.852095,6.621406,11.119750,0.168000
39,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-1.271857,-0.575201,10.438928,10.670837,7.216159,6.588926,10.874759,0.309001
40,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-0.092350,1.904261,9.949321,10.369358,6.231662,6.608001,10.695846,0.137900
41,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.339373,0.529931,10.652330,11.268520,7.540924,6.555357,11.485040,0.232299
42,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-0.369998,0.969150,8.323366,9.190852,7.129882,6.595781,11.228452,0.199000
43,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.126949,1.011655,7.826443,10.256536,1.840550,6.614726,11.752438,0.000501
44,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.017740,-1.071093,9.315871,9.575955,6.782634,6.602588,10.546578,0.277997
45,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-0.302292,-0.093477,8.007700,8.296547,7.110084,6.561031,11.491303,0.150000
46,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.072455,-0.263497,10.204259,10.619765,6.511552,6.612041,10.968267,0.139000
47,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.048294,-0.050972,9.958733,10.444852,7.698542,6.552528,11.124890,0.389894
48,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-1.271857,-1.467807,8.593043,8.612140,5.010369,6.499787,10.126671,0.071501
49,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-1.271857,1.649231,8.445697,8.946375,6.316894,6.593045,10.487434,0.184998

In [31]:
dummy_prep2.head()

,Loan_Status,Current_Loan_Amount,Years_of_Credit_History,Current_Credit_Balance_log,Maximum_Open_Credit_log,Monthly_Debt_log,Credit_Score_log,Annual_Income_log,di_ratio,Term_Long Term,...,Tax_Liens_2.0,Tax_Liens_3.0,Tax_Liens_4.0,Tax_Liens_5.0,Tax_Liens_6.0,Tax_Liens_7.0,Tax_Liens_8.0,Tax_Liens_9.0,Tax_Liens_10.0,Tax_Liens_11.0
0,0,-0.003618,-0.858568,8.818926,9.683900,6.371663,6.608001,10.425105,0.208000,0,...,0,0,0,0,0,0,0,0,0,0
1,0,-0.893036,1.125002,8.742415,9.860058,7.009445,6.598509,10.651833,0.314000,0,...,0,0,0,0,0,0,0,0,0,0
2,0,1.043230,1.479210,9.950753,10.251888,7.187544,6.616065,11.408975,0.176000,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0.791564,1.110833,10.022603,10.690034,6.623959,6.616065,10.547261,0.236999,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0.019611,-0.971915,9.763766,10.520887,5.875436,6.614726,10.820298,0.085201,0,...,0,0,0,0,0,0,0,0,0,0

In [32]:
data_scaled=data_scaled.drop(['Loan_Status'],axis=1)

# test train split before oversampling data

In [43]:
from sklearn.model_selection import StratifiedKFold
from sklearn.cross_validation import train_test_split as tts
x_train, x_val, y_train, y_val = tts(data_scaled,prep2['Loan_Status'],
                                                  test_size = .2,stratify=prep2['Loan_Status'],
                                                  random_state=42)
x_train.shape,x_val.shape,y_train.shape,y_val.shape

((172560, 127), (43140, 127), (172560,), (43140,))

In [44]:
print(y_train.value_counts(normalize=True))
print(y_val.value_counts(normalize=True))

0    0.816835
1    0.183165
Name: Loan_Status, dtype: float64
0    0.816829
1    0.183171
Name: Loan_Status, dtype: float64

# Oversampling By SMOTE

In [45]:
from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state=42, ratio =1.0)
X_train_res, Y_train_res = sm.fit_sample(x_train,y_train)
X_train_res.shape, Y_train_res.shape

/Users/SKYLER/anaconda3/lib/python3.6/site-packages/sklearn/utils/deprecation.py:77: DeprecationWarning: Function _ratio_float is deprecated; Use a float for 'ratio' is deprecated from version 0.2. The support will be removed in 0.4. Use a dict, str, or a callable instead.
  warnings.warn(msg, category=DeprecationWarning)

((281906, 127), (281906,))

In [46]:
y_train.value_counts(), np.bincount(Y_train_res)

(0    140953
 1     31607
 Name: Loan_Status, dtype: int64, array([140953, 140953]))

In [47]:
y_val.shape, 
y_val.value_counts()

0    35238
1     7902
Name: Loan_Status, dtype: int64

# Modeling

In [48]:
def Metrics(y_val,pred):
    print('accuray:', accuracy_score(y_val,pred),',recall score:',recall_score(y_val,pred),'\n ConfusionMatrix: \n',confusion_matrix(y_val,pred))
    #model_rf.feature_importances_
    print('Precision Score:',precision_score(y_val,pred),'F1_score:',f1_score(y_val,pred))

# Randomforest

In [49]:
from sklearn.metrics import accuracy_score,recall_score, confusion_matrix, roc_curve, precision_score, f1_score
from sklearn.ensemble import RandomForestClassifier #Random Forest

rf = RandomForestClassifier(n_estimators=50, min_samples_split=3, \
                            max_depth=3,random_state=42)
model_rf = rf.fit(X_train_res,Y_train_res)
pred_rf = model_rf.predict(x_val)
Metrics(y_val,pred_rf)

accuray: 0.988548910524 ,recall score: 0.99708934447
 ConfusionMatrix:
 [[34767   471]
 [   23  7879]]
Precision Score: 0.943592814371 F1_score: 0.969603741078

In [50]:
import pandas as pd
feature_importance_rf = pd.DataFrame(rf.feature_importances_,
                                   index = x_train.columns,
                                    columns=['importance']).sort_values('importance',ascending=False)

In [51]:
feature_importance_rf[0:10]

                              importance
Tax_Liens_11.0                  0.253245
Credit_Score_log                0.231115
Current_Loan_Amount             0.157315
Term_Long Term                  0.085326
Annual_Income_log               0.058901
di_ratio                        0.054677
Purpose_Medical Bills           0.020467
Years_of_Credit_History         0.019467
Purpose_Educational Expenses    0.017039
Purpose_Buy a Car               0.015144

In [52]:
from sklearn.ensemble import GradientBoostingClassifier 
g_clf = GradientBoostingClassifier(n_estimators=5,learning_rate=0.5,max_depth=3)
g_clf.fit(X_train_res,Y_train_res)
pred_g=g_clf.predict(x_val)
Metrics(y_val,pred_g)

accuray: 1.0 ,recall score: 1.0
 ConfusionMatrix:
 [[35238     0]
 [    0  7902]]
Precision Score: 1.0 F1_score: 1.0